CREATE DATABASE HabitHero;
USE HabitHero;

CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    CurrentLevel INT DEFAULT 1,
    XP INT DEFAULT 0
);

CREATE TABLE Levels (
    LevelID INT AUTO_INCREMENT PRIMARY KEY,
    LevelName VARCHAR(50) NOT NULL,
    XPThreshold INT NOT NULL
);

CREATE TABLE Habits (
    HabitID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT,
    HabitName VARCHAR(100) NOT NULL,
    Frequency ENUM('Daily', 'Weekly') NOT NULL,
    Category VARCHAR(50),
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE Completions (
    CompletionID INT AUTO_INCREMENT PRIMARY KEY,
    HabitID INT,
    UserID INT,
    DateCompleted DATE NOT NULL,
    StreakCount INT DEFAULT 0,
    FOREIGN KEY (HabitID) REFERENCES Habits(HabitID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE Rewards (
    RewardID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT,
    RewardType VARCHAR(100) NOT NULL,
    DateEarned DATE NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);





