debug: true
server:
  port: 6969

okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: https://dev-whftrzg80z4fcbt2.us.auth0.com/
    # Replace with the API Identifier for your Auth0 API.
    audience: habithero